In [ ]:
import numpy as np
x = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.itemsize

8

In [ ]:
import numpy as np
a = np.arange(4)
print(a+5)
print(a*10)


[5 6 7 8]
[ 0 10 20 30]


In [ ]:
import numpy as np
a = np.arange(4)
b = np.arange(4)
print(a+b)
print(a*b)

[0 2 4 6]
[0 1 4 9]


In [ ]:
import numpy as np
a=np.arange(1,30,2)
arr = np.array(a)
print(a)
arr.dtype

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


dtype('int64')